#!/bin/bash
set -e
cd "$(dirname "$0")"
find case -mindepth 1 -maxdepth 1 -type d -regextype posix-extended \
    -regex 'case/[0-9]+([.][0-9]+)?' -exec rm -rf -- {} +
rm -rf case/processor* case/postProcessing
rm -rf logs outputs .plotenv
rm -f case/*.OpenFOAM
